"""
Labelled visitor reviews (written by hand for training; realistic phrasing in Kannada, Hindi,
English and romanised text). Each: (text, sentiment, [aspects]).
sentiment: pos | neg | mix
aspects:   toilets  water  parking  crowd  guides  safety  food  access  heat
Real in-app reviews are added to this set after moderation; the evaluation below only uses
held-out examples (TEST) written separately from TRAIN.
"""
TRAIN = [
    # ── English ──
    ("The caves are stunning but the toilets near the entrance were filthy.", "mix", ["toilets"]),
    ("No drinking water anywhere on the way up to cave 4. Carry your own bottle.", "neg", ["water", "heat"]),
    ("Parking was full by 10 am and we circled for half an hour.", "neg", ["parking"]),
    ("Beautiful place, very peaceful early morning, hardly any crowd.", "pos", ["crowd"]),
    ("Our guide explained every carving so well, the kids loved it.", "pos", ["guides"]),
    ("Information boards are faded and hard to read.", "neg", ["guides"]),
    ("Felt safe even in the evening, there were security guards around.", "pos", ["safety"]),
    ("Some men were harassing girls near the lake, no police nearby.", "neg", ["safety"]),
    ("Tasty jolada rotti meal at a small hotel near the bus stand, very cheap.", "pos", ["food"]),
    ("Hardly any decent place to eat near Pattadakal.", "neg", ["food"]),
    ("Too many steps for my elderly parents, no railing at some places.", "neg", ["access"]),
    ("Pattadakal is flat and easy to walk, my father on a wheelchair managed well.", "pos", ["access"]),
    ("Extremely hot at noon and there is no shade near the temples.", "neg", ["heat"]),
    ("Clean washrooms and a drinking water point at the entrance, well maintained by ASI.", "pos", ["toilets", "water"]),
    ("Huge rush on Sunday, long queue at the ticket counter.", "neg", ["crowd"]),
    ("Loved the sunset at Agastya lake, magical.", "pos", []),
    ("Monkeys snatched our food bag, be careful.", "neg", ["safety", "food"]),
    ("Good parking space and the attendant was helpful.", "pos", ["parking"]),
    ("Road to Aihole is narrow and bumpy, and parking there is not organised.", "neg", ["parking"]),
    ("Amazing architecture, every temple is different. Must visit.", "pos", []),
    ("The museum was closed on Friday and nobody told us.", "neg", ["guides"]),
    ("Pravasi Mitra at the gate helped us plan the whole day.", "pos", ["guides"]),
    ("Dustbins overflowing and plastic everywhere near the caves.", "neg", ["toilets"]),
    ("Water cooler at Aihole was not working.", "neg", ["water"]),
    ("Went in December, weather was pleasant and crowd was manageable.", "pos", ["heat", "crowd"]),
    ("Nice place but vendors keep pestering you.", "mix", ["safety"]),
    ("Kids enjoyed climbing but it's slippery after rain.", "mix", ["safety", "access"]),
    ("Toilets were locked and there was no one to open them.", "neg", ["toilets"]),
    ("Plenty of shade under the trees at Mahakuta, great for families.", "pos", ["heat"]),
    ("Food was okay but overpriced near the monument.", "mix", ["food"]),
    # ── Kannada ──
    ("ಗುಹೆಗಳು ತುಂಬಾ ಸುಂದರವಾಗಿವೆ, ಆದರೆ ಶೌಚಾಲಯ ತುಂಬಾ ಗಲೀಜಾಗಿತ್ತು.", "mix", ["toilets"]),
    ("ಕುಡಿಯುವ ನೀರಿನ ವ್ಯವಸ್ಥೆ ಇಲ್ಲ, ಬಿಸಿಲಿನಲ್ಲಿ ತುಂಬಾ ಕಷ್ಟವಾಯಿತು.", "neg", ["water", "heat"]),
    ("ಪಾರ್ಕಿಂಗ್ ಜಾಗ ಸಿಗಲಿಲ್ಲ, ರಸ್ತೆ ಬದಿಯಲ್ಲಿ ಕಾರು ನಿಲ್ಲಿಸಬೇಕಾಯಿತು.", "neg", ["parking"]),
    ("ಬೆಳಿಗ್ಗೆ ಬೇಗ ಹೋದೆವು, ಜನ ಕಡಿಮೆ ಇದ್ದರು, ತುಂಬಾ ಚೆನ್ನಾಗಿತ್ತು.", "pos", ["crowd"]),
    ("ಮಾರ್ಗದರ್ಶಿ ಶಿಲ್ಪಗಳ ಕಥೆಯನ್ನು ಕನ್ನಡದಲ್ಲಿ ಸುಂದರವಾಗಿ ವಿವರಿಸಿದರು.", "pos", ["guides"]),
    ("ಮಾಹಿತಿ ಫಲಕಗಳು ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ಮಾತ್ರ ಇವೆ, ಕನ್ನಡದಲ್ಲಿ ಇಲ್ಲ.", "neg", ["guides"]),
    ("ಸಂಜೆ ಕೂಡ ಸುರಕ್ಷಿತ ಅನ್ನಿಸಿತು, ಭದ್ರತಾ ಸಿಬ್ಬಂದಿ ಇದ್ದರು.", "pos", ["safety"]),
    ("ಕೆರೆಯ ಬಳಿ ಕೆಲವರು ಹುಡುಗಿಯರಿಗೆ ತೊಂದರೆ ಕೊಡುತ್ತಿದ್ದರು, ಪೊಲೀಸರು ಇರಲಿಲ್ಲ.", "neg", ["safety"]),
    ("ಬಸ್ ನಿಲ್ದಾಣದ ಹತ್ತಿರ ಜೋಳದ ರೊಟ್ಟಿ ಊಟ ರುಚಿಯಾಗಿತ್ತು, ಬೆಲೆಯೂ ಕಡಿಮೆ.", "pos", ["food"]),
    ("ಪಟ್ಟದಕಲ್ಲಿನ ಹತ್ತಿರ ಒಳ್ಳೆಯ ಹೋಟೆಲ್ ಇಲ್ಲ.", "neg", ["food"]),
    ("ವಯಸ್ಸಾದ ಅಪ್ಪ ಅಮ್ಮನಿಗೆ ಮೆಟ್ಟಿಲು ಹತ್ತುವುದು ಕಷ್ಟವಾಯಿತು, ಹಿಡಿಕೆ ಇಲ್ಲ.", "neg", ["access"]),
    ("ಗಾಲಿಕುರ್ಚಿಯಲ್ಲಿ ಪಟ್ಟದಕಲ್ಲು ಸುತ್ತಾಡುವುದು ಸುಲಭವಾಗಿತ್ತು.", "pos", ["access"]),
    ("ಮಧ್ಯಾಹ್ನ ಬಿಸಿಲು ತುಂಬಾ ಜಾಸ್ತಿ, ನೆರಳು ಎಲ್ಲೂ ಇಲ್ಲ.", "neg", ["heat"]),
    ("ಶೌಚಾಲಯ ಸ್ವಚ್ಛವಾಗಿತ್ತು, ಕುಡಿಯುವ ನೀರೂ ಇತ್ತು.", "pos", ["toilets", "water"]),
    ("ಭಾನುವಾರ ಭಾರಿ ಜನಸಂದಣಿ, ಟಿಕೆಟ್‌ಗೆ ಉದ್ದದ ಸಾಲು.", "neg", ["crowd"]),
    ("ಅಗಸ್ತ್ಯ ತೀರ್ಥದ ಸೂರ್ಯಾಸ್ತ ಅದ್ಭುತ.", "pos", []),
    ("ಮಂಗಗಳು ಊಟದ ಚೀಲ ಕಸಿದುಕೊಂಡವು, ಎಚ್ಚರವಾಗಿರಿ.", "neg", ["safety", "food"]),
    ("ಪಾರ್ಕಿಂಗ್ ವ್ಯವಸ್ಥೆ ಚೆನ್ನಾಗಿತ್ತು.", "pos", ["parking"]),
    ("ಕಸದ ಬುಟ್ಟಿಗಳು ತುಂಬಿ ಪ್ಲಾಸ್ಟಿಕ್ ಎಲ್ಲೆಡೆ ಬಿದ್ದಿತ್ತು.", "neg", ["toilets"]),
    ("ಪ್ರವಾಸಿ ಮಿತ್ರರು ತುಂಬಾ ಸಹಾಯ ಮಾಡಿದರು.", "pos", ["guides"]),
    ("ವಾಸ್ತುಶಿಲ್ಪ ಅದ್ಭುತ, ಪ್ರತಿಯೊಂದು ದೇವಾಲಯವೂ ಬೇರೆ.", "pos", []),
    ("ನೀರಿನ ಘಟಕ ಕೆಲಸ ಮಾಡುತ್ತಿರಲಿಲ್ಲ.", "neg", ["water"]),
    ("ಮಳೆಯ ನಂತರ ಮೆಟ್ಟಿಲುಗಳು ಜಾರುತ್ತವೆ, ಮಕ್ಕಳೊಂದಿಗೆ ಎಚ್ಚರ.", "mix", ["safety", "access"]),
    ("ಮಹಾಕೂಟದಲ್ಲಿ ಮರಗಳ ನೆರಳು, ಕುಟುಂಬಕ್ಕೆ ಒಳ್ಳೆಯ ಜಾಗ.", "pos", ["heat"]),
    ("ಊಟ ಪರವಾಗಿಲ್ಲ, ಆದರೆ ಬೆಲೆ ಜಾಸ್ತಿ.", "mix", ["food"]),
    # ── Hindi ──
    ("गुफाएँ बहुत सुंदर हैं लेकिन शौचालय बहुत गंदे थे।", "mix", ["toilets"]),
    ("पीने के पानी की कोई व्यवस्था नहीं, गर्मी में बहुत परेशानी हुई।", "neg", ["water", "heat"]),
    ("पार्किंग फुल थी, आधा घंटा घूमते रहे।", "neg", ["parking"]),
    ("सुबह जल्दी गए, भीड़ बिल्कुल नहीं थी, बहुत शांत।", "pos", ["crowd"]),
    ("गाइड ने हर मूर्ति की कहानी बहुत अच्छे से समझाई।", "pos", ["guides"]),
    ("सूचना बोर्ड धुंधले हैं, पढ़ना मुश्किल है।", "neg", ["guides"]),
    ("शाम को भी सुरक्षित लगा, सुरक्षा कर्मी मौजूद थे।", "pos", ["safety"]),
    ("झील के पास कुछ लड़के परेशान कर रहे थे, पुलिस नहीं थी।", "neg", ["safety"]),
    ("बस स्टैंड के पास ज्वार की रोटी वाला खाना बहुत स्वादिष्ट और सस्ता था।", "pos", ["food"]),
    ("पट्टदकल के पास खाने की कोई अच्छी जगह नहीं है।", "neg", ["food"]),
    ("बुज़ुर्ग माता-पिता के लिए सीढ़ियाँ बहुत ज़्यादा हैं, रेलिंग नहीं है।", "neg", ["access"]),
    ("व्हीलचेयर के साथ पट्टदकल घूमना आसान था।", "pos", ["access"]),
    ("दोपहर में बहुत गर्मी और कहीं छाया नहीं।", "neg", ["heat"]),
    ("शौचालय साफ़ थे और पीने का पानी भी था।", "pos", ["toilets", "water"]),
    ("रविवार को भारी भीड़, टिकट के लिए लंबी लाइन।", "neg", ["crowd"]),
    ("अगस्त्य झील का सूर्यास्त शानदार था।", "pos", []),
    ("बंदरों ने हमारा खाने का थैला छीन लिया, सावधान रहें।", "neg", ["safety", "food"]),
    ("पार्किंग की व्यवस्था अच्छी थी।", "pos", ["parking"]),
    ("कूड़ेदान भरे हुए थे, हर जगह प्लास्टिक।", "neg", ["toilets"]),
    ("प्रवासी मित्र ने पूरा दिन प्लान करने में मदद की।", "pos", ["guides"]),
    ("वास्तुकला अद्भुत है, हर मंदिर अलग है।", "pos", []),
    ("पानी का कूलर खराब पड़ा था।", "neg", ["water"]),
    ("बारिश के बाद सीढ़ियाँ फिसलन भरी हैं।", "mix", ["safety", "access"]),
    ("खाना ठीक था लेकिन बहुत महँगा।", "mix", ["food"]),
    # ── romanised ──
    ("toilet tumba galiju ittu", "neg", ["toilets"]), ("kudiyo neeru illa, bisilu jaasti", "neg", ["water", "heat"]),
    ("parking sigalilla", "neg", ["parking"]), ("jana kammi idru, super experience", "pos", ["crowd"]),
    ("guide chennagi explain madidru", "pos", ["guides"]), ("oota tumba ruchi ittu", "pos", ["food"]),
    ("paani ki suvidha nahi thi", "neg", ["water"]), ("bheed bahut zyada thi", "neg", ["crowd"]),
    ("guide ne bahut accha samjhaya", "pos", ["guides"]), ("toilet bahut gande the", "neg", ["toilets"]),
]

TEST = [
    ("Washrooms were stinking, clearly not cleaned for days.", "neg", ["toilets"]),
    ("We could not find a single water tap near the temples.", "neg", ["water"]),
    ("Got a parking spot easily at 8 am.", "pos", ["parking"]),
    ("It was packed with school groups, hard to even see the Nataraja.", "neg", ["crowd"]),
    ("The audio guide in the app and the local guide were both excellent.", "pos", ["guides"]),
    ("A drunk man was shouting near the fort path, felt unsafe.", "neg", ["safety"]),
    ("Lovely north Karnataka thali near Banashankari.", "pos", ["food"]),
    ("No ramp anywhere, impossible with a wheelchair at the caves.", "neg", ["access"]),
    ("Scorching sun, carry an umbrella.", "neg", ["heat"]),
    ("Heritage is breathtaking but facilities need work.", "mix", []),
    ("ಶೌಚಾಲಯದಲ್ಲಿ ನೀರೇ ಇರಲಿಲ್ಲ, ತುಂಬಾ ಕೆಟ್ಟ ಸ್ಥಿತಿ.", "neg", ["toilets", "water"]),
    ("ವಾಹನ ನಿಲ್ಲಿಸಲು ಜಾಗವೇ ಇರಲಿಲ್ಲ.", "neg", ["parking"]),
    ("ಜನ ತುಂಬಾ ಇದ್ದರು, ಗುಹೆಯೊಳಗೆ ನಿಲ್ಲಲೂ ಜಾಗ ಇರಲಿಲ್ಲ.", "neg", ["crowd"]),
    ("ಮಾರ್ಗದರ್ಶಿ ತುಂಬಾ ಜ್ಞಾನಿ, ಚೆನ್ನಾಗಿ ವಿವರಿಸಿದರು.", "pos", ["guides"]),
    ("ರಾತ್ರಿ ಹೊತ್ತು ಬೆಳಕಿಲ್ಲ, ಭಯ ಆಯಿತು.", "neg", ["safety"]),
    ("ಹತ್ತಿರದ ಖಾನಾವಳಿಯ ಊಟ ಅದ್ಭುತ.", "pos", ["food"]),
    ("ಅಜ್ಜಿಗೆ ಮೆಟ್ಟಿಲು ಹತ್ತಲು ಆಗಲೇ ಇಲ್ಲ.", "neg", ["access"]),
    ("ಬಿಸಿಲಿನ ತಾಪ ತಡೆಯಲಾಗಲಿಲ್ಲ.", "neg", ["heat"]),
    ("ಸ್ಥಳ ಅದ್ಭುತ, ಸೌಲಭ್ಯ ಸುಧಾರಿಸಬೇಕು.", "mix", []),
    ("ಸ್ವಚ್ಛತೆ ಚೆನ್ನಾಗಿತ್ತು, ಖುಷಿ ಆಯಿತು.", "pos", ["toilets"]),
    ("शौचालय में पानी ही नहीं था।", "neg", ["toilets", "water"]),
    ("गाड़ी खड़ी करने की जगह नहीं मिली।", "neg", ["parking"]),
    ("इतनी भीड़ थी कि मूर्तियाँ ठीक से देख भी नहीं पाए।", "neg", ["crowd"]),
    ("गाइड बहुत जानकार थे।", "pos", ["guides"]),
    ("रात में रोशनी नहीं, डर लगा।", "neg", ["safety"]),
    ("पास के ढाबे का खाना बहुत बढ़िया।", "pos", ["food"]),
    ("दादी सीढ़ियाँ नहीं चढ़ पाईं।", "neg", ["access"]),
    ("धूप बर्दाश्त से बाहर थी।", "neg", ["heat"]),
    ("जगह शानदार है पर सुविधाएँ सुधरनी चाहिए।", "mix", []),
    ("सफ़ाई बहुत अच्छी थी।", "pos", ["toilets"]),
]

# Sample in-app reviews shown on the demo dashboard (clearly labelled as samples; not used for training or testing)
SAMPLES = [
    ("badami_caves", "Toilets near the cave entrance were dirty and there was no water.", 2),
    ("badami_caves", "ಗುಹೆಗಳು ಅದ್ಭುತ, ಆದರೆ ಕುಡಿಯುವ ನೀರು ಸಿಗಲಿಲ್ಲ.", 3),
    ("badami_caves", "Parking full on Sunday morning, waited 30 minutes.", 2),
    ("badami_caves", "गाइड ने बहुत अच्छे से समझाया, बच्चों को मज़ा आया।", 5),
    ("badami_caves", "Too many steps for my mother, no railing near cave 3.", 2),
    ("pattadakal", "Easy flat walk, great for elders. Loved the Virupaksha temple.", 5),
    ("pattadakal", "ಪಟ್ಟದಕಲ್ಲಿನ ಹತ್ತಿರ ಊಟಕ್ಕೆ ಒಳ್ಳೆಯ ಜಾಗ ಇಲ್ಲ.", 3),
    ("pattadakal", "No shade at noon, extremely hot.", 3),
    ("aihole", "Durga temple is stunning but the information boards are faded.", 4),
    ("aihole", "पार्किंग व्यवस्थित नहीं है, सड़क पर गाड़ी लगानी पड़ी।", 2),
    ("bhutanatha", "Sunset at Agastya lake was magical. Clean steps too.", 5),
    ("bhutanatha", "ಕೆರೆಯ ಬಳಿ ಸಂಜೆ ಬೆಳಕಿಲ್ಲ, ಸುರಕ್ಷಿತ ಅನ್ನಿಸಲಿಲ್ಲ.", 2),
    ("banashankari", "Huge crowd on Tuesday, long queue for darshan.", 3),
    ("mahakuta", "Peaceful, shady and clean. Perfect with family.", 5),
]
